version: '3.7'

services:
    postgres:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    mongodb:
        image: mongo:4.4.6
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: app_user
            MONGO_INITDB_ROOT_PASSWORD: app_password
            MONGO_INITDB_DATABASE: admin
        volumes:
        - ~/mongo:/data/db
        ports:
        - "27017:27017"
volumes:
    pgdata: